name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - uses: actions/cache@v3
        with:
          path: ~/.disco
          key: disco
      - run: composer test
